---
title: Events
---

You will be able to book onto events approximately **4 weeks in advance**.

We'll send updates to our mailing list when new booking forms are available.
Please make sure [you're signed up](mailing-list.qmd), if you'd like to get the announcements!

::: {#carers .callout-warning icon=false title='Support for parents and carers' collapse="true"}
HDRN is proud of fostering an inclusive community and wants to make sure our events are accessible to people with a range of different circumstances and needs. If you are a parent or carer affiliated to the University of Bristol, and would like to attend one of our workshops out of your normal working hours, we would be happy to support you.

Read more about it and register your interest here: [Parents and carers support form](https://forms.office.com/e/uh84hkhDLA)
:::

::: {.content-hidden}
<!--
This is a template event schedule.
Duplicate this content outside the {.content-hidden} block, rather than change this template.
Be sure to keep the `: {.schedule}` at the end, as this improves formatting on phone screens.
-->

Event     | Date                        | Time      | Location                         |
----------|-----------------------------|-----------|----------------------------------|--------------
Workshop  | Wednesday 1  January   2025 | 10am-2pm  | Engineers House, BS8 3BN         | [Agenda](events/w20250101.qmd) [Registration closed](){.btn .btn-sm .disabled}
Workshop  | Wednesday 1  February  2025 | 1-4pm     | Wills Memorial Building, BS8 1RJ | [Agenda](events/w20250102.qmd) [Register](https://forms.office.com/...){.btn .btn-sm .disabled}
Workshop  | Wednesday 10 September 2025 | 1-4pm     | Online                           | [Agenda](events/w20250910.qmd)

: {.schedule}
:::

Event     | Date                        | Time      | Location                         |
----------|-----------------------------|-----------|----------------------------------|--------------
Workshop  | Wednesday 12 March     2025 | 10am-2pm  | Engineers House, BS8 3BN         | [Slides and recordings](events/w20250312.qmd){.btn .btn-sm .btn-primary}
Workshop  | Thursday 10  April    2025 | 10am-1.30pm  | Wills Memorial Building, BS8 1RJ | [Slides and recordings](events/w20250410.qmd){.btn .btn-sm .btn-primary}
Seminar  | Wednesday 7  May       2025 | 11am-1.30pm  | Wills Memorial Building, BS8 1RJ | [Slides and recordings](events/s20250507.qmd){.btn .btn-sm .btn-primary}
Workshop  | Tuesday   3  June      2025 | 1.30pm-4pm  | Merchant Venturers Building, BS8 1UB | [Agenda](events/w20250603.qmd){.btn .btn-primary .btn-sm} [Register](https://forms.office.com/e/eNHSL2rRrU){.btn .btn-primary .btn-sm}
Workshop  | Wednesday 9  July      2025 | 10am-3.30pm  | Wills Memorial Building, BS8 1RJ                              | [Agenda](events/w20250709.html){.btn .btn-sm .disabled} [Register](https://forms.office.com/...){.btn .btn-sm .disabled}

: {.schedule}
