---
title: Seminar 7th May 2025
---

Health Data Research Network (HDRN) workshops are a forum space to advance and promote best and standardised practices in data access, handling, security, analysis and public engagement.
Our network is open to universities, governmental bodies, national research initiatives, health professionals, and industry.

Venue: Wills Memorial Building **3.32**, BS8 1RJ [///rich.bossy.square](https://what3words.com/rich.bossy.square)


::: {#carers .callout-warning icon=false title='Support for parents and carers' collapse="true"}
HDRN is proud of fostering an inclusive community and wants to make sure our events are accessible to people with a range of different circumstances and needs. If you are a parent or carer affiliated to the University of Bristol, and would like to attend one of our workshops out of your normal working hours, we would be happy to support you.

Read more about it and register your interest here: [Parents and carers support form](https://forms.office.com/e/uh84hkhDLA)
:::

<!--[Register](https://forms.office.com/e/){.btn .btn-primary}-->

## Agenda

*Chair: Pau Erola, Research Software Engineer, Jean Golding Institute, UoB*

<style>
    table {
        tr td:first-child { text-align: right; }
    }
</style>
<table class="table">
    <tr>
        <td>11:00</td>
        <td>Welcome</td>
    </tr>
    <tr>
        <td>11:05</td>
        <td>
            **David Western**, Wallscourt Fellow in Health Technology, University of the West of England

            [Machine Learning for Clinical EEG: Achieving State-of-the-Art Classifier Performance and Exploring Trustworthy Modes of Clinical Translation](../archive/s20250507/HDRN_20250507_01_DavidWestern.pdf)
            {{< video https://www.youtube-nocookie.com/embed/qoOEXJrMrKg >}}

        </td>
    </tr>
    <tr>
        <td>11:50</td>
        <td>
            Discussion<br>
            *ML and AI in translational health research*
        </td>
    </tr>
    <tr>
        <td>12:30</td>
        <td>Networking lunch</td>
    </tr>
</table>
