---
title: Workshop 10th April 2025
---

Health Data Research Network (HDRN) workshops are a forum space to advance and promote best and standardised practices in data access, handling, security, analysis and public engagement.
Our network is open to universities, governmental bodies, national research initiatives, health professionals, and industry.

Venue: Wills Memorial Building **3.32**, BS8 1RJ [///rich.bossy.square](https://what3words.com/rich.bossy.square)

<!--[Register](https://forms.office.com/e/){.btn .btn-primary}-->

::: {#carers .callout-warning icon=false title='Support for parents and carers' collapse="true"}
HDRN is proud of fostering an inclusive community and wants to make sure our events are accessible to people with a range of different circumstances and needs. If you are a parent or carer affiliated to the University of Bristol, and would like to attend one of our workshops out of your normal working hours, we would be happy to support you.

Read more about it and register your interest here: [Workshop 10th April parents and carers support form](https://forms.office.com/e/uh84hkhDLA)
:::

[Watch all talks on YouTube](https://www.youtube.com/playlist?list=PLx325CxArn14db8g2gizRRmZn5WLE2vl4){.btn .btn-primary}


## Agenda

*Chair: Pau Erola, Research Software Engineer, Jean Golding Institute, UoB*

<style>
    table {
        tr td:first-child { text-align: right; }
    }
</style>
<table class="table">
    <tr>
        <td>9:30</td>
        <td>Arrival -- self-service tea and coffee</td>
    </tr>
    <tr>
        <td>9:50</td>
        <td>Welcome</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>
            **Theresa Smith**, Senior Lecturer in Statistics, University of Bath  
            [Interpretable machine learning approaches for detecting psoriatic arthritis using electronic health records]()
            {{< video https://www.youtube-nocookie.com/embed/8wLH8hmZ0BE >}}

        </td>
    </tr>
    <tr>
        <td>10:30</td>
        <td>
            **Yi Liu**, Research Fellow, University of Bristol  
            [Annotated Semantic Queries and beyond](../archive/w20250410/HDRN_20250410_02_YiLiu.pdf)
            {{< video https://www.youtube-nocookie.com/embed/7GnSSsG05C8 >}}

        </td>
    </tr>
    <tr>
        <td>10:50</td>
        <td>Coffee break</td>
    </tr>
    <tr>
        <td>11:10</td>
        <td>
            **Romana Burgess**, Senior Research Associate, University of Bristol  
            [Using supermarket shopping data to track population health](../archive/w20250410/HDRN_20250410_03_RomanaBurgess.pdf)
            {{< video https://www.youtube-nocookie.com/embed/m85QeQOgyWA >}}

        </td>
    </tr>
    <tr>    
        <td>11:30</td>
        <td>
            **Laura Corbin**, Research Fellow, University of Bristol  
            [Discovery science using high-throughput metabolomics in clinical settings](../archive/w20250410/HDRN_20250410_04_LauraCorbin.pdf)
            {{< video https://www.youtube-nocookie.com/embed/iGxmliahl-0 >}}

        </td>
    </tr>
    <tr>
        <td>11:50</td>
        <td>Comfort break</td>
    </tr>
    <tr>
        <td>11:55</td>
        <td>
            Discussion<br>
            *ML and AI in health research and healthcare*
        </td>
    </tr>
    <tr>
        <td>12:30</td>
        <td>Networking lunch</td>
    </tr>
</table>
