---
title: Workshop 12th March 2025
---

Health Data Research Network (HDRN) workshops are a forum space to advance and promote best and standardised practices in data access, handling, security, analysis and public engagement.
Our network is open to universities, governmental bodies, national research initiatives, health professionals, and industry.

Venue: Engineers House, Bristol BS8 3NB [///dent.beyond.bridge](https://what3words.com/dent.beyond.bridge)

<!--
[Register](https://forms.office.com/e/jgi_KmVaRbpbSL){.btn .btn-primary}
-->

[Watch all talks on YouTube](https://www.youtube.com/playlist?list=PLx325CxArn14db8g2gizRRmZn5WLE2vl4){.btn .btn-primary}


## Agenda

*Chair: Pau Erola, Research Software Engineer, Jean Golding Institute, UoB*

|
----: | ------------------------------------------------------------------------
9.30  | Arrival -- self-service tea and coffee
10.00 | Welcome
10.10 | **Rachel Denholm**, Senior Lecturer, Bristol Medical School, UoB, and Co-Director of Health Data Research UK South West <br> *[The rise of new English Secure Data Environments](../archive/w20250312/HDRN_20250312_01_RachelDenholm.pdf)* <iframe width="560" height="315" src="https://www.youtube.com/embed/S0RBmuoucM4?si=crovRnA3DfTLmX6E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
10.30 | **Damon Chow**, Business Data Analyst, HDR UK <br> *[The Health Data Research Gateway](../archive/w20250312/HDRN_20250312_02_DamonChow.pdf)* <iframe width="560" height="315" src="https://www.youtube.com/embed/tAULRDMjJjI?si=V1USTyZSXTN-0XfG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
10.50 | Coffee break
11.10 | **Fiona Booth**, Data integrity & Quality Assurance Programme Director, UoB <br> *[Commercial vs. academic research approaches to reproducibility](../archive/w20250312/HDRN_20250312_03_FionaBooth.pdf)* <iframe width="560" height="315" src="https://www.youtube.com/embed/W3RmzJNAI1E?si=q2Gw47azpyGtVEGr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
11.30 | **Richard Welpton**, Head of Data Service Infrastructure, Economic and Social Research Council <br> *[Improving the experience of accessing sensitive data for research](../archive/w20250312/HDRN_20250312_04_RichardWelpton.pdf)* <iframe width="560" height="315" src="https://www.youtube.com/embed/qkXRGm62T68?si=qnTOPq_iZZWM5g95" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
11.50 | **Ben Elsworth**, Lead Data Engineer, Our Future Health <br> *[Processing and releasing genetic data at Our Future Health](../archive/w20250312/HDRN_20250312_05_BenElsworth.pdf)* <iframe width="560" height="315" src="https://www.youtube.com/embed/Ky2pYtui63c?si=UAK6AKAfKHJGY3jF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
12.10 | Break
12.20 | **Will Chapman**, Data Scientist, Jean Golding Institute <br> *[Routine data for health research](../archive/w20250312/HDRN_20250312_06_WillChapman.pdf)* <iframe width="560" height="315" src="https://www.youtube.com/embed/0d-C5dDi_7Q?si=rv7GlzGOAg5PLqW_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
12.40 | Q&A and round table <br> *Challenges in health data research: aims for the HDRN* 
13.00 | Networking lunch
