---
title: Workshop 9th July 2025
---

Health Data Research Network (HDRN) workshops are a forum space to advance and promote best and standardised practices in data access, handling, security, analysis and public engagement.
Our network is open to universities, governmental bodies, national research initiatives, health professionals, and industry.

Venue: Wills Memorial Building **3.32**, BS8 1RJ [///rich.bossy.square](https://what3words.com/rich.bossy.square)

<!--
[Register](https://forms.office.com/e/...){.btn .btn-primary}
-->

::: {#carers .callout-warning icon=false title='Support for parents and carers' collapse="true"}
HDRN is proud of fostering an inclusive community and wants to make sure our events are accessible to people with a range of different circumstances and needs. If you are a parent or carer affiliated to the University of Bristol, and would like to attend one of our workshops out of your normal working hours, we would be happy to support you.

Read more about it and register your interest here: [Parents and carers support form](https://forms.office.com/e/uh84hkhDLA)
:::

<!--[Watch all talks on YouTube](https://www.youtube.com/playlist?list=){.btn .btn-primary}-->


## Provisional Agenda

*Chairs:
<br>Serban Stoica, Consultant Cardiac Surgeon, University Hospitals Bristol NHS Foundation Trust <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Associate Professor in Congenital Cardiac Surgery, Bristol Medical School
<br>Miquel Perello-Nieto, Senior Research Associate, School of Engineering Mathematics and Technology
<br>Pau Erola, Research Software Engineer, Jean Golding Institute*

<style>
    table {
        tr td:first-child { text-align: right; }
    }
</style>
<table class="table">
    <tr>
        <td>9:30</td>
        <td>Arrival -- self-service tea and coffee</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Welcome
            <br>
            **Leon Danon**, Associate Professor in Data Analytics & Director of the Jean Golding Institute
            <br>
            **Patrick Kehoe**, Gestetner Professor of Translational Dementia Research & Director of Elizabeth Blackwell Institute
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <br><br>*Session 1, chair Serban Stoica*
        </td>
    </tr>

    <tr>
        <td>10:20</td>
        <td>
            **Maria Pufulete**, Associate Professor in Applied Health Methodology
        </td>
    </tr>
    <tr>
        <td>10:35</td>
        <td>
            **Giovanni Biglino**, Associate Professor in Bioengineering
        </td>
    </tr>
    <tr>
        <td>10:50</td>
        <td>
            **Dan Dorobantu**, Clinical Cardiology Fellow, University Hospitals Bristol NHS Foundation Trust
        </td>
    </tr>
    <tr>
        <td>11:05</td>
        <td>Coffee break <br><br><br>*Session 2, chair Pau Erola*</td>
    </tr>
 <tr>
        <td>11:25</td>
        <td>
            **Sarah Blake**, Cardiology Registrar in Adult Congenital Heart Disease, Royal Brompton and Harefield hospitals 
        </td>
    </tr>
    <tr>
        <td>11:40</td>
        <td>
            **Jack Gibb**, Cardiology Registrar, University Hospitals Bristol NHS Foundation Trust
        </td>
    </tr>
   <tr>
        <td>11:55</td>
        <td>
            **Colin McMahon**, Consultant in Cardiology, Children's Health Ireland at Crumlin;
            Professor in Paediatric Cardiology, University College Dublin
        </td>
    </tr>
    <tr>
        <td>12:05</td>
        <td>
            Discussion activity 
        </td>
    </tr>
    <tr>
        <td>12:30</td>
        <td>Networking Lunch <br><br><br>*Session 3, chair Miquel Perello-Nieto*</td>
    </tr>
    <tr>
        <td>1:30</td>
        <td>
            **James Pope**, Senior Lecturer, School of Engineering Mathematics and Technology
        </td>
    </tr>
    <tr>
        <td>1:45</td>
        <td>
            **Zhaozhen Xu**, Senior Research Associate in Machine Learning, Bristol Medical School
        </td>
    </tr>
    <tr>
        <td>2:00</td>
        <td>
            **Dan Lawson**, Associate Professor in Data Science, School of Mathematics
        </td>
    </tr>
    <tr>
        <td>2:15</td>
        <td>
            **Abigail Fraser**, Professor of Epidemiology, Bristol Medical School
        </td>
    </tr>
    <tr>
        <td>2:20</td>
        <td>Coffee break <br><br><br>*Session 4, chairs Serban & Pau*</td>
    </tr>
    <tr>
        <td>2:40</td>
        <td>
            Working group discussions
        </td>
    </tr>
    <tr>
        <td>3:15</td>
        <td>
            Recap & closing remarks
        </td>
    </tr>

</table>
